//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTYSproje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanismanTablosu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DanismanTablosu()
        {
            this.DersTablosu = new HashSet<DersTablosu>();
        }
    
        public int DanismanID { get; set; }
        public string İsimSoyisim { get; set; }
        public string Unvan { get; set; }
        public string Bolum { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DersTablosu> DersTablosu { get; set; }
    }
}
