//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTYSproje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DersSecimTablosu
    {
        public int DersSecimID { get; set; }
        public Nullable<int> OgrenciID { get; set; }
        public Nullable<int> DersID { get; set; }
        public Nullable<System.DateTime> SecmeTarihi { get; set; }
        public Nullable<bool> OnaylandiMi { get; set; }
    
        public virtual DersTablosu DersTablosu { get; set; }
        public virtual OgrenciTablosu OgrenciTablosu { get; set; }
    }
}
