//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTYSproje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DersTablosu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DersTablosu()
        {
            this.DersSecimTablosu = new HashSet<DersSecimTablosu>();
        }
    
        public int DersID { get; set; }
        public string DersKodu { get; set; }
        public string DersAdi { get; set; }
        public Nullable<bool> ZorunluMu { get; set; }
        public Nullable<int> DersKredi { get; set; }
        public string Bolum { get; set; }
        public Nullable<int> DanismanID { get; set; }
    
        public virtual DanismanTablosu DanismanTablosu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DersSecimTablosu> DersSecimTablosu { get; set; }
    }
}
