//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTYSproje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OgrenciTablosu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OgrenciTablosu()
        {
            this.DersSecimTablosu = new HashSet<DersSecimTablosu>();
        }
    
        public int OgrenciID { get; set; }
        public string İsim { get; set; }
        public string Soyisim { get; set; }
        public string Email { get; set; }
        public Nullable<int> DanismanID { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DersSecimTablosu> DersSecimTablosu { get; set; }
    }
}
