//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTYSproje.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VTYSprojeEntities : DbContext
    {
        public VTYSprojeEntities()
            : base("name=VTYSprojeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DanismanTablosu> DanismanTablosu { get; set; }
        public virtual DbSet<DersSecimTablosu> DersSecimTablosu { get; set; }
        public virtual DbSet<DersTablosu> DersTablosu { get; set; }
        public virtual DbSet<OgrenciTablosu> OgrenciTablosu { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
